#!/usr/bin/env bash

#LANZADOR DEL PROGRAMA SURICATAMAN
#ESTE SCRIPT LANZA EL PROGRAMA SURICATAMAN.SH QUE ES EL PROGRAMA PRINCIPAL
#PARA PODER EJECUTAR ESTE PROGRAMA SE DEBE TENER PERMISOS DE EJECUCION

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec bash "$SCRIPT_DIR/src/suricataman.sh" "$@"
